ENV["LC_ALL"] = "en_US.UTF-8"

$script_ng = <<-EOF
export LC_ALL=en_US.UTF-8
sudo yum -y update
sudo yum -y install wget
# sudo yum -y install java-1.8.0-openjdk
sudo yum -y install setroubleshoot setools
# sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
sudo wget -O /etc/yum.repos.d/nginx.repo https://raw.githubusercontent.com/zulus911/lectures/master/lecture2/nginx.repo
# sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
sudo yum -y install nginx net-tools policycoreutils-python
# sudo wget -O /etc/sysconfig/jenkins https://raw.githubusercontent.com/Cool04ek/lecture2/master/lecture2/jenkins
sudo wget -O /etc/nginx/conf.d/default.conf https://raw.githubusercontent.com/Cool04ek/lecture2/master/lecture2/default.conf
sudo setsebool -P httpd_can_network_connect 1
sudo semanage port -a -t http_port_t -p tcp 2222
sudo setsebool -P nis_enabled 1
# sudo service jenkins start
sudo systemctl start nginx
EOF

$script_jk1 = <<-EOF
export LC_ALL=en_US.UTF-8
sudo yum -y update
sudo yum -y install wget
sudo yum -y install java-1.8.0-openjdk
sudo yum -y install setroubleshoot setools
sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
# sudo wget -O /etc/yum.repos.d/nginx.repo https://raw.githubusercontent.com/zulus911/lectures/master/lecture2/nginx.repo
sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
sudo yum -y install jenkins net-tools policycoreutils-python
sudo wget -O /etc/sysconfig/jenkins https://raw.githubusercontent.com/Cool04ek/lecture2/master/lecture2/jenkins
# sudo wget -O /etc/nginx/conf.d/default.conf https://raw.githubusercontent.com/zulus911/lectures/master/lecture2/default.conf
sudo setsebool -P httpd_can_network_connect 1
sudo semanage port -a -t http_port_t -p tcp 2222
sudo setsebool -P nis_enabled 1
sudo service jenkins start
# sudo systemctl start nginx
EOF

$script_jk2 = <<-EOF
export LC_ALL=en_US.UTF-8
sudo yum -y update
sudo yum -y install wget
sudo yum -y install java-1.8.0-openjdk
sudo yum -y install setroubleshoot setools
sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
sudo yum -y install jenkins net-tools policycoreutils-python
sudo wget -O /etc/sysconfig/jenkins https://raw.githubusercontent.com/Cool04ek/lecture2/master/lecture2/jenkins
sudo setsebool -P httpd_can_network_connect 1
sudo semanage port -a -t http_port_t -p tcp 2222
sudo setsebool -P nis_enabled 1
sudo service jenkins start
EOF

Vagrant.configure("2") do |config|
  config.vm.define "nginx-vg" do |nginx|
    test.vm.box = "centos/7"
    test.vm.hostname = "stan.box"
    test.vm.network :private_network, ip:"192.168.14.88"
    test.vm.network :public_network, bridge: "en0: Wi-Fi (AirPort)", use_dhcp_assigned_default_route: true

    test.vm.provision "shell", inline: $script_ng
  end

  config.vm.define "jenkins1-vg" do |jenkins1|
    test.vm.box = "centos/7"
    test.vm.hostname = "stan.box"
    test.vm.network :private_network, ip:"192.168.0.14"

    test.vm.provision "shell", inline: $script_jk1
  end

  config.vm.define "jenkins2-vg" do |jenkins2|
    test.vm.box = "centos/7"
    test.vm.hostname = "stan.box"
    test.vm.network :private_network, ip:"192.168.0.88"

    test.vm.provision "shell", inline: $script_jk2
  end
end

